import { jsPDF } from "jspdf";

export interface ReceiptRow {
  label: string;
  value: string;
}

export function downloadReceiptPdf(fileName: string, title: string, rows: ReceiptRow[]) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });

  doc.setFillColor(10, 10, 10);
  doc.rect(0, 0, 595, 90, "F");

  doc.setFont("helvetica", "bold");
  doc.setTextColor(212, 175, 55);
  doc.setFontSize(22);
  doc.text("HeaveN8", 40, 48);

  doc.setFont("helvetica", "normal");
  doc.setTextColor(210, 210, 210);
  doc.setFontSize(10);
  doc.text("SIP. RESERVE. EXPERIENCE.", 40, 66);

  doc.setTextColor(30, 30, 30);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text(title, 40, 128);

  let y = 164;
  doc.setFontSize(11);

  rows.forEach((row) => {
    doc.setFont("helvetica", "bold");
    doc.setTextColor(70, 70, 70);
    doc.text(`${row.label}:`, 40, y);

    doc.setFont("helvetica", "normal");
    doc.setTextColor(30, 30, 30);
    const wrapped = doc.splitTextToSize(row.value || "-", 360);
    doc.text(wrapped, 190, y);

    const lineHeight = Math.max(22, wrapped.length * 14);
    y += lineHeight;

    doc.setDrawColor(228, 228, 228);
    doc.line(40, y - 10, 555, y - 10);
    y += 8;
  });

  doc.setTextColor(110, 110, 110);
  doc.setFont("helvetica", "italic");
  doc.setFontSize(10);
  doc.text("Generated by HeaveN8 secure checkout", 40, 800);

  doc.save(fileName);
}

